### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by jkm199** [LiLittleCat/awesome-free-chatgpt#1002]
#### 基本属性（单选）
- [ ] 🆓完全免费，打开即用
- [x] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

### 附加信息
完全仿官网gpt镜像站，新用户支持免费试用。

**Comment by LiLittleCat** [comment]
Thanks for the issue, but the site can’t be reached.
![image](https://github.com/user-attachments/assets/34f0dc98-949b-46e4-8546-df9b57af5635)
