### ISSUE TITLE
chat.muspimerol.site 被墙了，换成 index.chat.bnu120.space

### ISSUE THREAD

**Issue by CNSeniorious000** [LiLittleCat/awesome-free-chatgpt#116]
你好，我是 [chat.muspimerol.site](https://chat0.muspimerol.site/) 的站长，这个域名被墙有一段时间了，之后我们换了架构，新的线路就不再被墙了

但是为了防止被墙又要找你们这些索引站换，我们自己建了个新的入口来放我们不同的线路，所以希望你们能把此仓库中原来放 [chat.muspimerol.site](https://chat0.muspimerol.site/) 的位置改成 <https://index.chat.bnu120.space/>

我们还是做免登录、免费、免翻墙的服务；不仅自己网站在勤快更新，也给 chatgpt-demo(v1) 贡献了代码（包括修复了一个安全bug），但最近因为被墙损失了大半用户，特此请求修改索引，麻烦了！🙏

**Comment by LiLittleCat** [comment]
好的，感谢
