### ISSUE TITLE
作者不够勤快啊 审核也不够严格 大家可以来我这添加url

### ISSUE THREAD

**Issue by gochendong** [LiLittleCat/awesome-free-chatgpt#117]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/39932550/235046842-585c6847-ba36-4968-b4b0-670480ee60d7.png">
这是我对这个代码仓的所有url进行了进一步分析的结果
技术处理 + 手动处理 
大家如果有兴趣 可以直接在这个群里留言 
[布里塔](https://chat.bullita.cn)
我比较闲 能够更快的更新 (使用匿名一键登录 无需注册)

**Comment by gochendong** [comment]
https://chat.bulita.cn/

**Comment by LiLittleCat** [comment]
最近有点忙，五一优化一下

**Comment by gochendong** [comment]
在这里提mr也是一样的 我会实时抓取这个代码仓的 嘿嘿
