### ISSUE TITLE
提交一个免费用的chatgpt

### ISSUE THREAD

**Issue by SeanWenkui** [LiLittleCat/awesome-free-chatgpt#141]
1.  [🆓] [https://seven-star.org/](https://seven-star.org/)
2. 关注公众号即可登录，登录就有7天的免费使用期
3. 免费积分用完后可以，可以去邀请朋友，邀请者和被邀请者都可以获得14天的使用权。所以理论上你可以一直免费用下去的

**Comment by LiLittleCat** [comment]
@SeanWenkui 感谢提供
