### ISSUE TITLE
提交一个可免费使用的网站

### ISSUE THREAD

**Issue by TangSY** [LiLittleCat/awesome-free-chatgpt#144]
网址：https://ai.hxkj.vip
无限制使用次数，免国际网络，类chatgpt官网界面，同时扩展了各种角色扮演、生产力、娱乐应用，满足特定场景的需求。内置的【暴躁老哥】玩得很上火，哈哈哈

**Comment by LiLittleCat** [comment]
@TangSY 感谢提供
