### ISSUE TITLE
网站收录

### ISSUE THREAD

**Issue by hehan-wang** [LiLittleCat/awesome-free-chatgpt#150]
网址

[chat.wenwen-ai.com](https://chat.wenwen-ai.com/)
网站类型：
ai绘画，聊天

网站简介、使用方式：
需要注册

是否需要国际网络(可选)
 否

**Comment by LiLittleCat** [comment]
感谢提供

**Comment by hehan-wang** [comment]
[https://chat.wenwen-ai.com](https://chat.wenwen-ai.com/) 
亲你少写了https 无法跳转哈
![image](https://github.com/LiLittleCat/awesome-free-chatgpt/assets/18670007/245e43ee-a924-470d-8bc5-52201b90a4ba)

**Comment by LiLittleCat** [comment]
@hehan-wang 哦哦，好的
