### ISSUE TITLE
收录并且合作

### ISSUE THREAD

**Issue by aa122655** [LiLittleCat/awesome-free-chatgpt#160]

**Comment by aa122655** [comment]
网址：1919abc.com    合作微信yy88558831

**Comment by LiLittleCat** [comment]
@aa122655 你好，页面操作时报错 `404: 请求的资源不存在~`

**Comment by aa122655** [comment]
没有报错啊，

Yi Liu ***@***.***> 于2023年5月15日周一 23:48写道：
