### ISSUE TITLE
自建免费GPT-4网站，申请收录

### ISSUE THREAD

**Issue by rggt5656** [LiLittleCat/awesome-free-chatgpt#161]
申请收录，谢谢！完全免费。目前账号有2500美元的余额，已经拿到GPT-4权限。
[gpt4.gravityengine.cc](https://gpt4.gravityengine.cc)

**Comment by rggt5656** [comment]
目前打算开放每月500美元左右的使用额度，欢迎体验。

**Comment by LiLittleCat** [comment]
@rggt5656 very good

**Comment by Bobcole12345** [comment]
Nice！
