### ISSUE TITLE
新增网址

### ISSUE THREAD

**Issue by hi-zhaoyeqing** [LiLittleCat/awesome-free-chatgpt#162]
国内可用，永久免费
https://static-mp-ab12aa38-c762-407c-a145-732b237ae0bb.next.bspapp.com

**Comment by LiLittleCat** [comment]
@hi-zhaoyeqing 你好，显示 IP 不在白名单 `{"success":false,"error":{"code":"ClientIpNotAllowed","message":"Your clientIp *** does not in the whitelist."}}`
