### ISSUE TITLE
新增网站

### ISSUE THREAD

**Issue by edmondsket** [LiLittleCat/awesome-free-chatgpt#17]
https://ai.cheapy.top
这个网站可以用，需要注册，有免费对话

**Comment by LiLittleCat** [comment]
@edmondsket 感谢

**Comment by edmondsket** [comment]
网站好像被墙了，换成了https://ai.ptlife.eu.org/这个网址

**Comment by LiLittleCat** [comment]
> 网站好像被墙了，换成了https://ai.ptlife.eu.org/这个网址

OK，感谢
