### ISSUE TITLE
The website I created can provide free gpt for Chinese users：aidaguan.com

### ISSUE THREAD

**Issue by CatAnd-Dog** [LiLittleCat/awesome-free-chatgpt#176]
The website I created can provide free gpt for Chinese users：aidaguan.com

_Originally posted by @aidaguan in https://github.com/LiLittleCat/awesome-free-chatgpt/issues/175#issuecomment-1554607597_
            

你可以收录和分享以及使用我的网站，它是完全免费的，而且它和普通的5美元账户有很大的区别，因为它几乎不会受到速率的限制。

**Comment by LiLittleCat** [comment]
@CatAnd-Dog 您好，暂不收录此类网站，此仓库专注于免费开箱即用的 ChatGPT 镜像站，您可以在其他收录该类网站的项目提交，谢谢。
