### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by rackmelts** [LiLittleCat/awesome-free-chatgpt#237]
### 网址
https://carps.ink

#### 基本属性（单选）
- [ ] 🆓完全免费，打开即用
- [x] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [x] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

### 附加信息
无需魔法，国内可用，支持AI绘画，支持联网搜索，谷歌搜索，必应搜索，支持多达60余种角色对话，支持语音合成，多达60余种AI语音。后续会支持文档对话等等。

**Comment by rackmelts** [comment]
大佬，似乎有点小错误，不需要关注公众号，我看到有个眼睛的emoji，表示需要关注公众号。

**Comment by LiLittleCat** [comment]
哦，是需要登录是吧，搞错了

**Comment by rackmelts** [comment]
啊，大佬回复这么快，是的是的，感谢大佬
