### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by hehan-wang** [LiLittleCat/awesome-free-chatgpt#244]
### 网址

http://chat.wenwen-ai.com/ 
可以成为赞助商
#### 基本属性（单选）
- [ ] 🆓完全免费，打开即用
- [x] 🔓有免费额度
- [x] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [x] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by LiLittleCat** [comment]
你好，已经收录，谢谢
