### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by sodamnsure** [LiLittleCat/awesome-free-chatgpt#252]
#### 基本属性（单选）
- [ ] 🆓完全免费，打开即用
- [x] 🔓有免费额度
- [x] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [ ] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by LiLittleCat** [comment]
@sodamnsure 你好，无法访问诶

**Comment by sodamnsure** [comment]
@LiLittleCat 啊，没办法访问吗，你把VPN关了试试呢，我这边能访问

**Comment by LiLittleCat** [comment]
@sodamnsure 关了的，等下换个机器试试
