### ISSUE TITLE
如果您不想您的网站出现在此，请在这个 issue 下评论。If you do not want your site to appear here, please comment under this issue.

### ISSUE THREAD

**Issue by LiLittleCat** [LiLittleCat/awesome-free-chatgpt#26]

**Comment by huanfeng123** [comment]
小旋风chat 域名被墙原始域名 http://gpt.gpt0.icu/
新域名：https://gpt.ai8.icu/

**Comment by LiLittleCat** [comment]
> 小旋风chat 域名被墙原始域名 http://gpt.gpt0.icu/ 新域名：https://gpt.ai8.icu/

已修改，感谢提供

**Comment by 88lin** [comment]
https://ai.mcbbs.gq/ 麻烦替换为 https://521.zeabur.app/

**Comment by usechatgptlive** [comment]
投稿 https://chat.free2gpt.xyz 无需魔法 无需登录 不限次数 无弹窗广告 就该如此方便简洁

**Comment by golangboy** [comment]
chatgpt.bybyte.cn 修改为 zuoai.live

**Comment by wejudging** [comment]
投稿 https://chat.meizi.me 无魔法 无登录 无限制
