### ISSUE TITLE
这个也可以用

### ISSUE THREAD

**Issue by lovetingyuan** [LiLittleCat/awesome-free-chatgpt#3]
https://ai.okmiku.com/chat

**Comment by LiLittleCat** [comment]
@lovetingyuan 感谢，你要提交 PR 贡献吗？不的话我就加上了

**Comment by lovetingyuan** [comment]
> @lovetingyuan 感谢，你要提交 PR 贡献吗？不的话我就加上了

你加嘛 多谢
