### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by gengtianuiowa** [LiLittleCat/awesome-free-chatgpt#322]
### 网址
https://chat.immuseai.com

#### 基本属性（单选）
- [ ] 🆓完全免费，打开即用
- [X ] 🔓有免费额度
- [X ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [X ] 💪支持 GPT4
- [X ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by LiLittleCat** [comment]
已收录
