### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by Yuan-Lin615** [LiLittleCat/awesome-free-chatgpt#356]
### 网址
zhiziera.com

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [ ] 🔓有免费额度
- [x] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [ ] 💪支持 GPT4
- [x] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by Yansre** [comment]
网址
g01.plitun.com

属性
基本属性（单选）
🆓完全免费，打开即用
