### ISSUE TITLE
添加镜像站点  https://99.opao.xyz/

### ISSUE THREAD

**Issue by cat-dog-fish** [LiLittleCat/awesome-free-chatgpt#366]
### 附加信息
多个版本均无限制免费使用。多种模型可以使用。还有联网功能，newbing均为免费

https://99.opao.xyz/

使用了120美刀账号。没有任何速率限制，访问速度飞快。
每分钟的回复次数高达三千次。（免费5刀账户只有3次）

没有任何使用限制。可以自定义模型参数。自由度超高。
麻烦作者增加一下推荐权重，谢谢。承诺永久免费使用。

https://99.opao.xyz/

What's New:

Password access removed, out of the box.

I used a $120 account. There is no speed limit and access is fast.

There are as many as 3,000 replies per minute. (Free $5 account only 3 times)

There are no restrictions on use. You can customize the model parameters. High degree of freedom.

Please kindly ask the author to increase the recommended weight, thank you. Promise to use it free forever.

**Comment by haifengzuishuai** [comment]
![image](https://github.com/LiLittleCat/awesome-free-chatgpt/assets/46316222/e18ce558-768b-40d0-bbf5-9ccdfb4484ad)
这叫无限制免费使用吗。。。

**Comment by CatAnd-Dog** [comment]
> ![image](https://user-images.githubusercontent.com/46316222/250437714-e18ce558-768b-40d0-bbf5-9ccdfb4484ad.png) 这叫无限制免费使用吗。。。

这是4.0，你可以看一下你的套餐，3.5是无限制免费的。。。。。。。。你可以先去用了之后，再来评论
