### ISSUE TITLE
添加站点 chatgpt-api-web

### ISSUE THREAD

**Issue by heimoshuiyu** [LiLittleCat/awesome-free-chatgpt#41]
<https://heimoshuiyu.github.io/chatgpt-api-web/?key=fakekey&api=https%3A%2F%2F3lio5ooiekcn3gxx6du2jf5wzq0mudmm.lambda-url.us-east-1.on.aws%2F&mode=fetch>

URL 参数中提供了一个免费的 API key 和 Lambda 中转服务 ，无需代理，只有 gpt-3.5 可用，不可用 stream 模式。

如果需要gpt-4或者stream模式可以更换自己的 API key

**Comment by LiLittleCat** [comment]
@heimoshuiyu 感谢提供
