### ISSUE TITLE
更新失效站点

### ISSUE THREAD

**Issue by pky2006** [LiLittleCat/awesome-free-chatgpt#42]
实测这 5 个站点均已失效
[ 🆓 ] http://gitopenchina.gitee.io/gpt

[ 🆓 ] http://gitopenchina.gitee.io/chatgpt

[ 🆓 ] http://gitopenchina.gitee.io/freechatgpt

[ 🆓 ] https://ai.bo-e.com/

[ 🆓🌎 ] https://freegpt.one/

**Comment by LiLittleCat** [comment]
@pky2006 感谢提供信息
