### ISSUE TITLE
站点更新

### ISSUE THREAD

**Issue by yitd** [LiLittleCat/awesome-free-chatgpt#45]
https://www.tdchat.com/
已经更换为新站点http://www.tdchat.vip/
不需要梯子，免费不限制次数GPT3.5，GPT-4每日可免费用3次

**Comment by LiLittleCat** [comment]
@yitd 感谢提供

**Comment by yitd** [comment]
如有订单问题请截图付款记录，发联系方式。原网址已被封，GPT-4已上线，请保存新的TDChat入口网址：http://tdchat.de（地址发布页-收藏不迷路）http://tdchat.im（地址发布页-收藏不迷路）http://tdchat.nethttp://tdchat.vip备用美国线路：https://w.tdchat.us/商城地址是：http://pays.tdchat.de/
