### ISSUE TITLE
ChatGPT中文

### ISSUE THREAD

**Issue by 740400019** [LiLittleCat/awesome-free-chatgpt#47]
网址
http://a.aizh.app/

网站类型
ChatGPT站点

是否需要国际网络(可选)
否

ico 路径
https://camo.githubusercontent.com/ca54604e6873602da61c4dedda5c4f58a4c7453a22b61fb7655c75e7408efbf4/68747470733a2f2f73742e616935352e63632f66617669636f6e2f7971636c6f75642e746f702e737667

使用方式(可选)
 登录使用，有限使用次数

**Comment by LiLittleCat** [comment]
@740400019 感谢提供
