### ISSUE TITLE
好多镜像，怎么知道是什么版本呢？

### ISSUE THREAD

**Issue by henbucuoshanghai** [LiLittleCat/awesome-free-chatgpt#567]
3.5？还是4？在哪看？

**Comment by VMCoud** [comment]
![image](https://github.com/LiLittleCat/awesome-free-chatgpt/assets/59264435/fa29b8d1-a098-4da2-b482-8b46e2a089ed)
[https://Gpt.freet.top/](https://gpt.freet.top/#/?settings={%22key%22:%22%22,%22url%22:%22/api/openai1/%22})

**Comment by LiLittleCat** [comment]
> 3.5？还是4？在哪看？

前面有 emoji 标识
