### ISSUE TITLE
 [README]  chat.muspimerol.site is out of service

### ISSUE THREAD

**Issue by moHaHa** [LiLittleCat/awesome-free-chatgpt#58]
![image](https://user-images.githubusercontent.com/72744132/232372743-60c918ad-e290-4680-bdf4-ff46a35519b6.png)

**Comment by LiLittleCat** [comment]
@moHaHa Thank you for your feedback. However, I just tested it and it appears to still be available.
![image](https://user-images.githubusercontent.com/40536573/232396118-78874ee0-81b7-4826-adea-4cf418e23d7b.png)

**Comment by moHaHa** [comment]
you're right, I think the owner did fix it  ✅
