### ISSUE TITLE
标识GPT版本或者支持其他AI的版本？

### ISSUE THREAD

**Issue by ElisaMin** [LiLittleCat/awesome-free-chatgpt#6]
* [ 🆓 ] 使用没有限制  
* [ 🔐 ] 有限使用，需要输入 API key 或登录  
* [ 🌎 ] 需要科学上网  
* [ 🆕 ] GPT-4 Support  
* [ ✖️ ] 不只是GPT

**Comment by LiLittleCat** [comment]
@ElisaMin Good idea，您可以参与贡献吗？非常感谢！
