### ISSUE TITLE
反馈站点失效

### ISSUE THREAD

**Issue by h1xy** [LiLittleCat/awesome-free-chatgpt#607]
### 原因

- [ ] 🚫无法正常打开
- [ ] ❌功能异常
- [x] 🤔其他：
删除

**Comment by LiLittleCat** [comment]
@h1xy 你好，还需要删除吗？我看你把 issue 关了

**Comment by h1xy** [comment]
> @h1xy 你好，还需要删除吗？我看你把 issue 关了

先不用，网站稳住了，感谢

**Comment by LiLittleCat** [comment]
> > @h1xy 你好，还需要删除吗？我看你把 issue 关了
> 
> 先不用，网站稳住了，感谢

OK
