### ISSUE TITLE
https://ai.bo-e.com/ 不能使用

### ISSUE THREAD

**Issue by yesaiwen2008** [LiLittleCat/awesome-free-chatgpt#63]
这是官方的公告：
尊敬的博弈Ai用户：

非常抱歉、难过又痛心的通知您：由于我司Ai系统未经评估已上线，安全风险隐患较大。遵网信部门的指导，依据中华人民共和国《网络安全法》、《具有舆论属性或社会动员能力的互联网信息服务安全评估规定》，我们已于2023年04月11日中午12点整，暂时关停网站的Ai对话功能！

待我们合规整改、并按照网信主管部门要求，履行相关的安全评估程序后，再次向公众重新开放。

**Comment by LiLittleCat** [comment]
@yesaiwen2008 OK，感谢
