### ISSUE TITLE
添加镜像站点:aivesa.cn

### ISSUE THREAD

**Issue by ClarenceDan** [LiLittleCat/awesome-free-chatgpt#631]
### 网址
https://aivesa.cn/

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [x] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [x] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

### 附加信息
网站已稳定运行半年，全球直连无需国际网络，目前支持免费不限量的GPT-3.5，GPT-4.0和讯飞星火大模型，欢迎使用，欢迎体验。

**Comment by laris** [comment]
- [ ] -  🆓完全免费?
- [ ] -  🔒需要登陆?
