### ISSUE TITLE
idea会自动关闭

### ISSUE THREAD

**Issue by jackfanwan** [LiLittleCat/awesome-free-chatgpt#665]
### 原因

- [x] ❌功能异常
![image](https://github.com/LiLittleCat/awesome-free-chatgpt/assets/61672564/a9e2d364-e8b6-427f-8940-5659fd9e440c)
点这个插件的时候 就会自动关闭idea，我的版本是2023.2.5
![image](https://github.com/LiLittleCat/awesome-free-chatgpt/assets/61672564/8e7c24fa-553a-4cd1-96b8-a5f636db2ca6)

**Comment by LiLittleCat** [comment]
请在 [此处](https://github.com/LiLittleCat/intellij-chatgpt/issues) 提 issue，此项目非插件项目，谢谢。
