### ISSUE TITLE
这个也是免费的https://www.nav4ai.com/chatgpt

### ISSUE THREAD

**Issue by MrShellad** [LiLittleCat/awesome-free-chatgpt#67]
这个也是免费的https://www.nav4ai.com/chatgpt

**Comment by LiLittleCat** [comment]
@MrShellad 感谢贡献，但是我发现 Cookie 检查失败
![image](https://user-images.githubusercontent.com/40536573/232800776-6f30fc74-c69e-4624-830e-067d0743ea6a.png)

**Comment by MrShellad** [comment]
> @MrShellad 感谢贡献，但是我发现 Cookie 检查失败 ![image](https://user-images.githubusercontent.com/40536573/232800776-6f30fc74-c69e-4624-830e-067d0743ea6a.png)

我这边测试正常欸

**Comment by LiLittleCat** [comment]
明天换个网络环境试试
