### ISSUE TITLE
添加镜像站点  https://chat.aiptl.com  重点是免费支持GPT-4

### ISSUE THREAD

**Issue by Somnus1437** [LiLittleCat/awesome-free-chatgpt#699]
### 网址
https://chat.aiptl.com

### 属性

重点是免费支持GPT-4 
无需注册 无需国际网络 

#### 基本属性（单选）
- [x]  🆓完全免费，打开即用
- [x]  🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x]  💪支持 GPT4
- [x]  🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by xiao-mantou** [comment]
戴了4.0mask的3.0？
