### ISSUE TITLE
反馈站点失效

### ISSUE THREAD

**Issue by h1xy** [LiLittleCat/awesome-free-chatgpt#766]
34	https://coffeecat.ai 需要key
23	https://free.aitom.cc/ 没有免费
28	https://chat-shared2.zhile.io/ 潘多拉关闭
29	https://chat.geekgpt.org/ 潘多拉关闭
4	https://chat.atmoses.uk/ 无法使用
16	https://beta.aicatgirl.com/ 密码无效
15	https://ct10.xiami.monster/ 网站出错
14	https://chat.aiptl.com 网站打不开
8	https://chat.meizi.me 和下面重复
9	https://chat.meizi.me

**Comment by LiLittleCat** [comment]
谢谢，辛苦了
