### ISSUE TITLE
反馈站点失效

### ISSUE THREAD

**Issue by h5xy** [LiLittleCat/awesome-free-chatgpt#817]
1	http://chat5.aiyunos.top  gpt-4需赞助
2	https://newpc.icoding.ink/?debug=true gpt-4带广告不回答
5	http://nmwaicg.top/ 没有免费gpt-4
8	https://ss.sbai.free.hr/ 跳转 15	https://hai.dongstop.link/ 重复
9	https://chat.meizi.me  域名失效
11	https://chat.ai365vip.com/ gpt-4需付费
12	https://www.aitool.ink/  抱歉，当前接口响应超时，请稍后再试

**Comment by LiLittleCat** [comment]
Thanks a lot
