### ISSUE TITLE
反馈站点失效

### ISSUE THREAD

**Issue by tw1720** [LiLittleCat/awesome-free-chatgpt#826]
### 网址
239 https://gpt6.fun/
242 	https://www.bz1y.cn/
243 https://beta.bushiai.com/ (導向到 https://ai.ltsat.cn/ 🔒)
245 https://gpt.opengpt88.com/
246 https://tubogpt.vercel.app/
247 https://seven-star.org/
248 https://chat.hehanwang.com/
249 https://chat.8kg.co/

### 原因

- [x] 🚫无法正常打开
- [ ] ❌功能异常
- [ ] 🤔其他：

**Comment by LiLittleCat** [comment]
Thanks a lot
