### ISSUE TITLE
https://chat.ohtoai.com/ 无法使用

### ISSUE THREAD

**Issue by yesaiwen2008** [LiLittleCat/awesome-free-chatgpt#83]
无法使用。打开后，出现维护通知：

维护通知：

由于涉及违规信息输出，我们将暂时停止ChatGPT Next Web的运行

为了维护互联网安全和健康发展，我们郑重提醒您:任何用户都不允许在ChatGPT Next Web生产、发布、传播任何违法、违规内容

一旦发现用户发布、输出、传播涉及国家法律法规禁止的涉及政治、色情、暴力、恐怖主义、谣言等相关内容，只要发现一起，我们将立即采取严厉措施，记录用户IP地址并永久封禁。同时，我们会配合有关部门进行调查和报警处理，保障网络信息安全和秩序良好

预计维护3-5天

**Comment by LiLittleCat** [comment]
感谢
