### ISSUE TITLE
添加镜像站点 (已經取消關注仍然收到添加鏡像站的郵件)

### ISSUE THREAD

**Issue by hunandy14** [LiLittleCat/awesome-free-chatgpt#845]
已經取消關注仍然收到添加鏡像站的郵件
請問該如何避免收到這個gihub的郵件?

我找不到可以取消訂閱的地方
如果是請幫我取消，每天一直寄信太煩了
如果不是可以請教該如何取消這個awesome-free-chatgpt來自這個倉庫的 issues 嗎?

**Comment by LiLittleCat** [comment]
![image](https://github.com/LiLittleCat/awesome-free-chatgpt/assets/40536573/982001d0-3c3f-4164-b756-003d1c9a80d1)
try this
