### ISSUE TITLE
收录提交，和官网一模一样的，而且免费不限次数。

### ISSUE THREAD

**Issue by nxisp** [LiLittleCat/awesome-free-chatgpt#85]
网址是：http://chaosu.vip
和官网一模一样的，而且免费不限次数。速度很快。专人维护，保证稳定。

**Comment by seanM29** [comment]
朋友 这个网址是不是错了 我打不开

**Comment by LiLittleCat** [comment]
我也打不开 😕

**Comment by zhujunqiang2007** [comment]
博主可以看下我们团队制作的，免注册，不需要科学上网：https://chat.bootai.top/ 求收录。可试用卡密：478138

**Comment by clayboby** [comment]
补一个我知道带GPT4的
https://www.vivi-chat.com/#/chat 
挺快挺好用
关注一波公众号，应该经常有白嫖活动

**Comment by LiLittleCat** [comment]
> 478138

卡密已过期了

**Comment by qdzhaoxiaodao** [comment]
> 补一个我知道带GPT4的 https://www.vivi-chat.com/#/chat 挺快挺好用 关注一波公众号，应该经常有白嫖活动

还要关注公众号，麻烦，哈哈

**Comment by AngelOver** [comment]
推荐一个 永久免费、不限次数的  https://1chat.cc
