### ISSUE TITLE
添加工具：iMessage AI助手（ChatGPT国内最简单访问方式，免费，免翻墙，免安装，免注册）

### ISSUE THREAD

**Issue by yvonuk** [LiLittleCat/awesome-free-chatgpt#870]
### [网址]
[iMessage AI助手](https://stockai.trade/chat)
通过苹果设备（iPhone/iPad/Mac）的iMessage与ChatGPT对话聊天

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [x] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by autoabokless** [comment]
。

**Comment by LiLittleCat** [comment]
只收录镜像站点，谢谢
