### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by kldhsh123** [LiLittleCat/awesome-free-chatgpt#891]
### 网址
https://myai.asia/

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [ ] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [x] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

### 附加信息

**Comment by kldhsh123** [comment]
你好,我的不仅仅是 Chat的标签没有正确的被添加

**Comment by LiLittleCat** [comment]
> 你好,我的不仅仅是 Chat的标签没有正确的被添加

👌

**Comment by kldhsh123** [comment]
好的谢谢
