### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by wfce** [LiLittleCat/awesome-free-chatgpt#915]
### 网址
https://free.gptapi.us/

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [ ] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by jiangbajin** [comment]
你好！我是JYQin！您的邮件已经收到！！！

**Comment by LiLittleCat** [comment]
@wfce 请求失败
![image](https://github.com/user-attachments/assets/de4f7c64-5822-4ea5-b4de-7049cc23a844)
