### ISSUE TITLE
基于自建知识库的开源 AI 搜索引擎

### ISSUE THREAD

**Issue by ahaapple** [LiLittleCat/awesome-free-chatgpt#921]
https://github.com/memfreeme/memfree

## Introduction

MemFree is a hybrid AI search engine that simultaneously performs searches on your personal knowledge base (such as bookmarks, notes, documents, etc.) and the Internet.

## Highlights

- Hybrid AI Search Engine
- One-Click Chrome Bookmarks Sync and Index
- Support multiple traditional search engines as source
- Self-hosted Super Fast Serverless Vector Database
- Self-hosted Super Fast Local Embedding and Rerank Service
- Full Code Open Source
- One-Click Deployment On Production

**Comment by LiLittleCat** [comment]
Good, but not suitable for this repository.
