### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by mvfeng** [LiLittleCat/awesome-free-chatgpt#929]
### 网址
https://hao.94c.cn       好导航94c，免费chatgpt，打开即用无需登录无限制，2024/08/01

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [ ] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [ ] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by LiLittleCat** [comment]
It's good, but not suitable for this repository. see #235, thank you for understanding.
