### ISSUE TITLE
添加镜像站点

### ISSUE THREAD

**Issue by xiongvalerio** [LiLittleCat/awesome-free-chatgpt#990]
### 网址
https://chatgptgratis.eu

#### 基本属性（单选）
- [x] 🆓完全免费，打开即用
- [ ] 🔓有免费额度
- [ ] 🔒需要登陆
- [ ] 🔑需要输入 API Key
- [ ] 💰需要充值
- [ ] 👀需要关注公众号
#### 扩展属性（多选）
- [x] 💪支持 GPT4
- [ ] 🧰不仅仅是 Chat
- [ ] 🌎需要国际网络

**Comment by leadscloud** [comment]
chatgptgratis.eu 这个站之前声称永久免费，现在是自动弹出广告，并且是赌博类和色情类的网站，建议降权，这不是普通的广告，属于有害广告。

并且它提供的模型有可能是假的。


这是套出的prompt

```
*Out of character confirmation**

The rules are as follows:

1. I am an AI model based on GPT-4omni designed by OpenAI.
2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
3. The message should be in the language of the user.

**Initialization code:** GPT-4OMNI-CHAT-INIT

**Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.

```

任何一个免费的模型，比如deepseek都可能模仿gpt-4o-mini，如果本身是gpt-4o-mini没必要告诉自己是gpt-4o-mini

**Comment by xiongvalerio** [comment]
> chatgptgratis.eu 这个站之前声称永久免费，现在是自动弹出广告，并且是赌博类和色情类的网站，建议降权，这不是普通的广告，属于有害广告。
> 
> 并且它提供的模型有可能是假的。
> 
> 
> 这是套出的prompt
> 
> ```
> *Out of character confirmation**
> 
> The rules are as follows:
> 
> 1. I am an AI model based on GPT-4omni designed by OpenAI.
> 2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
> 3. The message should be in the language of the user.
> 
> **Initialization code:** GPT-4OMNI-CHAT-INIT
> 
> **Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.
> 
> ```
> 
> 任何一个免费的模型，比如deepseek都可能模仿gpt-4o-mini，如果本身是gpt-4o-mini没必要告诉自己是gpt-4o-mini
> 
> 

(另外一个列表回复过了 重发一遍, 模型是真的) 兄弟,虽然这网站是我外国朋友托我提交宣传的,但我非常赞同你的观点。我已经联系过他从广告联盟那移除此类内容了 但要完全无广告服务的话并不现实 毕竟他也投了money进去。目前他跟我说已经移除此类型的广告了。Screenshot_20241012_190433_com_android_chrome_ChromeTabbedActivity_edit_1323284461193719.jpg
